### ISSUE TITLE
type "timestamp" is not supported

### ISSUE THREAD

**Issue by hatemzidi** [lulco/phoenix#153]
i was dumping an existing database under mysql and i got this error : 

> In Column.php line 84:
> Type "timestamp" is not allowed.

after checking Database/Element/Column.php, i added manually the constant, and it seems to work properly.

is there any constraints to not add this type (timestamp) ?

**Comment by lulco** [comment]
Hello,
thank you for using Phoenix!

Column type timestamp was not added just because I personally don't use it. But if you want, feel free to create Pull request adding this type for both - dumping and creating column.

It should be added to these src files:
- src/Database/Element/Column.php
- src/Database/QueryBuilder/MysqlQueryBuilder.php
- src/Database/QueryBuilder/PgsqlQueryBuilder.php

and these test files:
- tests/Database/QueryBuilder/MysqlQueryBuilderTest.php
- tests/Database/QueryBuilder/PgsqlQueryBuilderTest.php
- testing_migrations/phoenix/20150529123120_init.php

**Comment by lulco** [comment]
@hatemzidi hello, will you try to add this type or should I?

**Comment by hatemzidi** [comment]
@lulco sorry for the late reply, 
in fact, i'm currently in holidays, i'll try to PR this when i'm back (during septembre).
thanks.

**Comment by lulco** [comment]
@hatemzidi Hi, I just added support for timestamp column type. It's merged in master. Could you please confirm it works as expected before I create new release? Thank you very much.
