### ISSUE TITLE
Can't fetchAll where column IS [NOT] NULL

### ISSUE THREAD

**Issue by Kal-Aster** [lulco/phoenix#254]
Hi, I think the title says all.

In the functions AbstractMigration::fetch and ::fetchAll as well in Adapter::fetch and ::fetchAll there isn't the argument `where` but nly `conditions`, so it's not possible to specify a where clause like `column IS NOT NULL`, because saying `[ 'column' => 'NOT NULL' ]` as condition will result in `column = NOT NULL` which is not what I need

**Comment by lulco** [comment]
Hi @Kal-Aster,
Thanks for report. Yes you're right. Fetch and fetchAll don’t have the where statement. You can use `select()` method for this purpose.

Or feel free to send pull request with adding this feature to fetch / fetchAll $conditions parameter

**Comment by Kal-Aster** [comment]
Should I PR on master?

**Comment by lulco** [comment]
You need to fork phoenix and then create PR

**Comment by lulco** [comment]
And yes, you can use master as base / target branch

**Comment by Kal-Aster** [comment]
I was working on this and thought I came to a solution, but right now I don't think it'll work...

I'll explain the problem, hoping someone can help me to find a better solution.
Having to fetch where `NULL` is quite simple: you check if `$value` is `null` and use `' IS '` instead of `' = '`, but having to fetch where `NOT NULL` is trickier... I thought that a solution would be to check if `$value == 'NOT NULL'` but this can't work because if someone wants to fetch where a column is the string `'NOT NULL'` it will convert the condition to `column IS NOT NULL` instead of `column = 'NOT NULL'`, which is quite different...

I think that a proper way to solve this would be to introduce a "unique" constant, but I don't know where to place it to be consistent with the rest of the code.

**Comment by lulco** [comment]
What about to use column part for comparator too?

`'column !=' => null` will be tranfered to `is not null`
`'column >' => 123` will mean `column > 123`
etc.

`=` will be default and should not be required because of back compatibility

space between column name and comparator will be required

there is no need to use keywords like `IS`, `IS NOT`, `IN` etc because we can handle them with `=`, `!=`

the only limitation here is for users who use column names with space but I am ok with it at this point

**Comment by lulco** [comment]
Closed by https://github.com/lulco/phoenix/pull/255
