### ISSUE TITLE
Class Phoenix\Migration\Init\Init located in src\Migration\Init\0_init.php does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by NetesiCTO** [lulco/phoenix#288]
Hello,
Composer show this message when I include your project: Class Phoenix\Migration\Init\Init located in src\Migration\Init\0_init.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by lulco** [comment]
Hi, tes that's correct. It is caused by the fact that migrations are created with snake_case name and with timestamp and class inside has CamelCase name. Migrations are inculded separately by require once in https://github.com/lulco/phoenix/blob/ea847891df43bd91eb8f83d5b6e3c8097a18a3e6/src/Migration/Manager.php#L120
