### ISSUE TITLE
Is this a fork of phinx?

### ISSUE THREAD

**Issue by edsonmedina** [lulco/phoenix#74]
It looks exactly the same

https://phinx.org/

**Comment by lulco** [comment]
@edsonmedina no, this is not a fork of phinx. Public API is very similar but not the same. And all code in background is different. The reason why public API looks like phinx's is that I use phinx before and I wanted to switch to phoenix as easy as possible. If you have any question, I'll try to answer.

**Comment by edsonmedina** [comment]
Thanks for the clarification.
Not trying to demean your project. I just thought it was too similar (both api and name).

Is there a reason why you chose to start this as opposed to use (or contribute to) phinx?

**Comment by lulco** [comment]
Yes, there were few reasons.
- First of all was that it takes too long time while support for multiple migration paths was merged into phinx (PR 488).
- Also it was kind of challenge for me. I wanted to try if I am able to code something like phinx but in my way. I wanted to create phoenix with some features from the beginning (multiple migration folders, namespaces for migration classes, validation of all table settings before first query is executed etc. so that's why I didn't contribute to phinx)

**Comment by edsonmedina** [comment]
I see. Thanks. 
Looks good so far.
